### ISSUE TITLE
tried it, that scrolling is kinda weird

### ISSUE THREAD

**Issue by vegarringdal** [wakaDemo/wListView#10]
why are you creating new list items on scroll?
why not just set top value, and data?

**Comment by wakaDemo** [comment]
Setting top value would involve handling the scrolling ourselves and manipulating the DOM on scroll: that's what we wanted to avoid with this widget which is a test case for mobile-ready widget.

DOM has to be manipulated when reaching the end of the list (and the list has to fetch and insert data), but once it's done, scrolling to the top is native and doesn't involve any code from the widget.

This may appear weird when compared to the current listview or grid widget, but isn't that weird if you imagine an email list, or twitter/facebook articles list.
